return {
	{
		"AstroNvim/astroui",
		---@type AstroUIOpts
		opts = {
			icons = {
				ActiveLSP = "",
				ActiveTS = " ",
				BufferClose = "",
				DapBreakpoint = "",
				DapBreakpointCondition = "",
				DapBreakpointRejected = "",
				DapLogPoint = "",
				DapStopped = "",
				DefaultFile = "",
				Diagnostic = "",
				DiagnosticError = "",
				DiagnosticHint = "",
				DiagnosticInfo = "",
				DiagnosticWarn = "",
				Ellipsis = "",
				FileModified = "",
				FileReadOnly = "",
				FoldClosed = "",
				FoldOpened = "",
				FolderClosed = "",
				FolderEmpty = "",
				FolderOpen = "",
				Git = "",
				GitAdd = "",
				GitBranch = "",
				GitChange = "",
				GitConflict = "",
				GitDelete = "",
				GitIgnored = "",
				GitRenamed = "",
				GitStaged = "",
				GitUnstaged = "",
				GitUntracked = "",
				LSPLoaded = "",
				MacroRecording = "",
				Paste = "",
				Search = "",
				Selected = "",
				TabClose = "",
				-- configure the loading of the lsp in the status line
				LSPLoading1 = "⠋",
				LSPLoading2 = "⠙",
				LSPLoading3 = "⠹",
				LSPLoading4 = "⠸",
				LSPLoading5 = "⠼",
				LSPLoading6 = "⠴",
				LSPLoading7 = "⠦",
				LSPLoading8 = "⠧",
				LSPLoading9 = "⠇",
				LSPLoading10 = "⠏",
				VimIcon = "",
				ScrollText = "",
			},
		},
	},
	{
		"onsails/lspkind.nvim",
		opts = function(_, opts)
			-- use codicons preset
			opts.preset = "codicons"
			-- set some missing symbol types
			opts.symbol_map = {
				Array = "",
				Boolean = "",
				Key = "",
				Namespace = "",
				Null = "",
				Number = "",
				Object = "",
				Package = "",
				String = "",
			}
		end,
	},
}
