# Reference: https://github.com/i3/i3/blob/next/etc/config

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers                         = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# janky borders
# https://github.com/FelixKratz/JankyBorders
after-startup-command = [
  # JankyBorders has a built-in detection of already running process,
  # so it won't be run twice on AeroSpace restart
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]

# Layouts for workspaces
exec-on-workspace-change = ['/bin/bash', '-c', """
  if [ "$AEROSPACE_FOCUSED_WORKSPACE" = "1" ]; then
    aerospace layout v_accordion
  elif [ "$AEROSPACE_FOCUSED_WORKSPACE" = "2" ]; then
    aerospace layout h_tiles
  elif [ "$AEROSPACE_FOCUSED_WORKSPACE" = "3" ]; then
    aerospace layout v_tiles
  fi
  """]

# Start AeroSpace at login
start-at-login = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
  inner.horizontal = 20
  inner.vertical   = 20
  outer.bottom     = 20
  outer.left       = 20
  outer.right      = 20
  outer.top        = 20

# https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
  1 = ['^built-in retina display$', 'main']
  2 = ['^m15*', 'dell', 'secondary']
  3 = ['^sidecar', 'lg', 3]

[mode.main.binding]
  # All possible keys:
  # - Letters.        a, b, c, ..., z
  # - Numbers.        0, 1, 2, ..., 9
  # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
  # - F-keys.         f1, f2, ..., f20
  # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
  #                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
  # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
  #                   keypadMinus, keypadMultiply, keypadPlus
  # - Arrows.         left, down, up, right

  # All possible modifiers: cmd, alt, ctrl, shift

  # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

  cmd-alt-h = [] # Disable "hide others"
  cmd-h     = [] # Disable "hide application"

  alt-shift-ctrl-j     = 'fullscreen'
  alt-shift-ctrl-l     = 'resize height -50'
  alt-shift-ctrl-quote = 'resize height +50'
  alt-shift-ctrl-u     = 'resize width -50'
  alt-shift-ctrl-y     = 'resize width +50'

  alt-shift-ctrl-m = 'mode service'
  # i3 wraps focus by default
  alt-shift-ctrl-e = 'focus --boundaries-action wrap-around-the-workspace down'
  alt-shift-ctrl-i = 'focus --boundaries-action wrap-around-the-workspace up'
  alt-shift-ctrl-n = 'focus --boundaries-action wrap-around-the-workspace left'
  alt-shift-ctrl-o = 'focus --boundaries-action wrap-around-the-workspace right'

  alt-shift-ctrl-k = 'workspace-back-and-forth'
  # move windows
  alt-shift-ctrl-comma  = 'move down'
  alt-shift-ctrl-h      = 'move left'
  alt-shift-ctrl-period = 'move up'
  alt-shift-ctrl-slash  = 'move right'

  # Not supported, because this command is redundant in AeroSpace mental model.
  # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
  #alt-space = 'focus toggle_tiling_floating'

  # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
  # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
  # alt-a = 'focus parent'

  alt-shift-ctrl-b = 'move-node-to-workspace 5'
  alt-shift-ctrl-f = 'move-node-to-workspace 3'
  alt-shift-ctrl-p = 'move-node-to-workspace 4'
  alt-shift-ctrl-q = 'move-node-to-workspace 1'
  alt-shift-ctrl-w = 'move-node-to-workspace 2'

  alt-shift-ctrl-a = 'workspace 1'
  alt-shift-ctrl-g = 'workspace 5'
  alt-shift-ctrl-r = 'workspace 2'
  alt-shift-ctrl-s = 'workspace 3'
  alt-shift-ctrl-t = 'workspace 4'

  # See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
  f13 = 'exec-and-forget open -a /Applications/Signal.app/'
  f14 = 'exec-and-forget open -a /Applications/Discord.app/'
  f15 = 'exec-and-forget open -a /Applications/WezTerm.app/'
  f16 = 'exec-and-forget open -a /Applications/Brave\ Browser.app/'
  f17 = 'exec-and-forget open -a /Applications/Slack.app/'
  f18 = 'exec-and-forget open -a /Applications/ChatGPT.app/'
  f19 = 'exec-and-forget open -a /Applications/Claude.app/'
  f20 = 'exec-and-forget open -a /Applications/Obsidian.app/'

[mode.service.binding]
  esc = 'mode main'
  # --
  l     = 'layout accordion'           # toggle accordion/tiles/floating layout
  quote = 'layout horizontal vertical' # toggle horizontal/vertical layout
  u     = 'layout tiles'
  y     = 'layout floating'
  # --
  e = 'join-with down'
  i = 'join-with up'
  n = 'join-with left'
  o = 'join-with right'
  # --
  j = ['close-all-windows-but-current', 'mode main']
  k = ['mode main', 'reload-config']
  m = [
    'flatten-workspace-tree',
    'layout accordion vertical',
    'mode main',
  ] # resets the workspace tree and sets the layout to vertical accordion

# ------------------------------------------------------------
# Window detection rules
# use mdls -name kMDItemCFBundleIdentifier /Applications/APP_NAME.app
# for example w/ brave:
# mdls -name kMDItemCFBundleIdentifier -r /Applications/Brave\ Browser.app
[[on-window-detected]]
  if.app-id = 'com.apple.FaceTime'
  run       = ['layout floating', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.valvesoftware.steam'
  run       = ['layout floating', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  run       = ['layout floating', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.github.wez.wezterm'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.openai.chat'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'ai.perplexity.mac'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.docker.docker'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.figma.Desktop'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.apple.MobileSMS'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.tinyspeck.slackmacgap'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'com.hnc.Discord'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'org.whispersystems.signal-desktop'
  run       = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
  if.app-id = 'md.obsidian'
  run       = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
  if.app-id = 'com.anthropic.claudefordesktop'
  run       = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
  if.app-id = 'com.valvesoftware.dota2'
  run       = ['layout floating', 'move-node-to-workspace 2']

[[on-window-detected]]
  if.app-id = 'com.brave.Browser'
  run       = ['layout tiling', 'move-node-to-workspace 3']

[[on-window-detected]]
  if.app-id = 'com.apple.finder'
  run       = ['layout tiling', 'move-node-to-workspace 3']
