# Inserts a blank line between shell prompts
add_newline = false
# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '
# Move the directory to the second line
format = '$username$hostname$git_commit$git_branch$git_status$all$character'
# move the rest of the prompt to the right
right_format = '$directory⍆ $time'

[line_break]
  disabled = false

[character]
  error_symbol   = "[❯❯](bold #ff0033)"
  success_symbol = "[❯❯](bold green)"

[cmd_duration]
  # Show command duration over 10,000 milliseconds (= 10 sec)
  format   = "took [$duration]($style)"
  min_time = 120_000

[directory]
  format            = '[$read_only]($read_only_style)[$path]($style) '
  read_only         = " "
  read_only_style   = "#AB2330"
  style             = "bold #EEEEEE"
  truncate_to_repo  = true
  truncation_length = 20
  truncation_symbol = ""

[git_branch]
  format            = ' [$symbol$branch(:$remote_branch)]($style)  '
  style             = "dimmed blue"
  symbol            = " "
  truncation_length = 20
  truncation_symbol = ""

[git_commit]
  commit_hash_length = 10

[git_status]
  ahead    = '⇡${count}'
  behind   = '⇣${count}'
  diverged = '⇕⇡${ahead_count}⇣${behind_count}'

[username]
  disabled    = false
  format      = "[$user]($style) "
  show_always = false
  style_root  = "#ED2B2A"
  style_user  = "#36454F"

[hostname]
  disabled = false
  format   = "« [$hostname](bold #FF4C29) » "
  ssh_only = true
  trim_at  = ".companyname.com"

[status]
  disabled = false
  format   = '\[[$symbol$status]($style)\] '
  style    = "#cc0000"
  symbol   = "status-code: "

[time]
  disabled    = false
  format      = "[$time]($style) "
  style       = "#667C76"
  time_format = "%T"

#-------------------------------- non-common languages -------------------------------
[aws]
  disabled = true
  format   = '\[AWS: [$symbol$profile/($region)]($style)\] '
  style    = 'dimmed white'
  symbol   = ""

[docker_context]
  disabled = false
  format   = "[$symbol$context](green) "
  symbol   = ""

[gcloud]
  disabled = true
  format   = '\[GCP: [$symbol$account(@$domain)(\($project\))]($style)\] '
  style    = 'dimmed white'
  symbol   = " "

[golang]
  disabled       = false
  format         = '[$symbol ($version)]($style) '
  style          = 'cyan'
  symbol         = ''
  version_format = 'v${raw}'

[kubernetes]
  disabled = true
  format   = '\[k8s: [$context\($namespace\)](dimmed green)\] '

[lua]
  format = '[$symbol $version](cyan) '
  symbol = ""

[conda]
  symbol = " "

[dart]
  symbol = " "

[elixir]
  symbol = " "

[elm]
  symbol = " "

[hg_branch]
  symbol = " "

[java]
  symbol = " "

[julia]
  symbol = " "

[memory_usage]
  symbol = " "

[nim]
  symbol = " "

[nix_shell]
  symbol = " "

[nodejs]
  format = '[$symbol($version )]($style) '
  symbol = ' '

[package]
  disabled = true
  format   = '[$symbol$version]($style) '
  symbol   = " "

[perl]
  symbol = " "

[php]
  symbol = " "

[python]
  symbol = " "

[ruby]
  symbol = " "

[rust]
  symbol = " "

[scala]
  symbol = " "

[shlvl]
  symbol = " "

[swift]
  symbol = "ﯣ "
