# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[❯❯](bold green)"
error_symbol = "[❯❯](bold #ff0033)"

[aws]
symbol = ""
disabled = true
style = 'dimmed white'
format = '\[AWS: [$symbol$profile/($region)]($style)\] '

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

[directory]
style = "bold #EEEEEE"
read_only = " "
read_only_style = "#AB2330"
format = ': [$read_only]($read_only_style)[$path]($style) '
truncation_length = 10
truncation_symbol = ""
truncate_to_repo = true

[docker_context]
symbol = ""
format = "[$symbol$context](green) "

[gcloud]
disabled = true
symbol = " "
style = 'dimmed white'
format = '\[GCP: [$symbol$account(@$domain)(\($project\))]($style)\] '

[git_branch]
symbol = "-"
style = "dimmed blue"
format = '\([$symbol$branch]($style)\) '
truncation_length = 10
truncation_symbol = ""

[git_commit]
commit_hash_length = 10

[golang]
symbol = ""
disabled = false
style = "cyan"
format = "[$symbol ($version)]($style) "

[hostname]
ssh_only = true
format =  "on [$hostname](bold #FF4C29) "
trim_at = ".companyname.com"
disabled = false

[kubernetes]
disabled = true
format = '\[k8s: [$context\($namespace\)](dimmed green)\] '

[lua]
symbol = ""
format = '[$symbol $version](cyan) '

[status]
disabled = false
style = "#cc0000"
symbol = "status-code: "
format = '\[[$symbol$status]($style)\] '

[time]
disabled = false
style = "#667C76"
time_format = "%T"
format = "[$time]($style) "

[username]
style_user = "#36454F"
style_root = "#36454F"
format = "[$user]($style) "
disabled = false
show_always = true

#-------------------------------- non-common languages -------------------------------
[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
