# Inserts a blank line between shell prompts
add_newline = false
# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '
# Move the directory to the second line
format = '$username$hostname$git_commit$git_branch$git_status$all$character'
# move the rest of the prompt to the right
right_format = '$directory⍆$time'

[line_break]
disabled = true

[character]
success_symbol = "[❯❯](bold green)"
error_symbol = "[❯❯](bold #ff0033)"

[cmd_duration]
min_time = 120_000                  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

[directory]
style = "bold #EEEEEE"
read_only = " "
read_only_style = "#AB2330"
format = '[$read_only]($read_only_style)[$path]($style) '
truncation_length = 20
truncation_symbol = ""
truncate_to_repo = true

[git_branch]
symbol = " "
style = "dimmed blue"
format = '⟦[$symbol$branch(:$remote_branch)]($style)⟧ '
truncation_length = 20
truncation_symbol = ""

[git_commit]
commit_hash_length = 10

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[username]
style_user = "#36454F"
style_root = "#ED2B2A"
format = "[$user]($style)"
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "◈[$hostname](bold #FF4C29)~>"
trim_at = ".companyname.com"
disabled = false

[status]
disabled = false
style = "#cc0000"
symbol = "status-code: "
format = '\[[$symbol$status]($style)\] '

[time]
disabled = false
style = "#667C76"
time_format = "%T"
format = "[$time]($style) "

#-------------------------------- non-common languages -------------------------------
[aws]
symbol = ""
disabled = true
style = 'dimmed white'
format = '\[AWS: [$symbol$profile/($region)]($style)\] '

[docker_context]
symbol = ""
format = "[$symbol$context](green) "

[gcloud]
disabled = true
symbol = " "
style = 'dimmed white'
format = '\[GCP: [$symbol$account(@$domain)(\($project\))]($style)\] '

[golang]
symbol = ""
disabled = false
style = "cyan"
format = "[$symbol ($version)]($style) "

[kubernetes]
disabled = true
format = '\[k8s: [$context\($namespace\)](dimmed green)\] '

[lua]
symbol = ""
format = '[$symbol $version](cyan) '

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = ' '
format = '[$symbol($version )]($style) '

[package]
symbol = " "
format = '[$symbol$version]($style) '

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
